### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by tempestade** [twilio-labs/plugin-flex#64]
I'm having this message on twilio-cli/2.11.0 win32-x64 node-v10.15.1

Invoking any command that uses network I get this:

[DEBUG] self signed certificate in certificate chain
[DEBUG] Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1051:34)
    at TLSSocket.emit (events.js:189:13)
    at TLSSocket._finishInit (_tls_wrap.js:633:8)

I don't know why certificate is not being verified by authority

**Comment by ktalebian** [comment]
@tempestade what command are you invoking exactly? Also, would you check the time/clock setting on your computer? If your computer clock/time is out of sync, you may get this certification error.

**Comment by tempestade** [comment]
@ktalebian I'm trying do deploy a plugin... but any command that need network connection.

**Comment by ktalebian** [comment]
@tempestade there may be something wrong with your local installation of OpenSSL. It looks like you have custom certificate files and OpenSSL is rejecting it. 

I'm not too familiar with Windows OS and SSL but let me ask someone on the CLI team regarding this since this is unrelated to this extension. 

In the meantime, I suggest Googling for SSL issues with Windows and how you can fix that.

**Comment by tempestade** [comment]
@ktalebian Could make requests using following:

set NODE_TLS_REJECT_UNAUTHORIZED=0

It should have validate a proper certificate though!
Maybe something is missing in twilio-cli implementation

**Comment by tempestade** [comment]
Problem is a custom certificate in a proxy issued by my company. [SOLVED]
